### ISSUE TITLE
Express-Featherjs example

### ISSUE THREAD

**Issue by aguilera51284** [roboncode/orango#16]
I would like to see how it would be integrated into a framework.

**Comment by roboncode** [comment]
Sure thing. As I am working on the examples, I will provide an example with Express since that seems to be the most common framework.

**Comment by roboncode** [comment]
0.7.0 has the start of some examples. If you download or clone the project you can run it using

With an instance of ArangoDB running

```bash
cd examples/express
node samples.js
node app.js
```

I will continue to work on the examples. Also you can look at the test cases to lean how to use some of the other features of the API while the docs are in development.
