### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by redyce** [roboncode/orango#35]
Hello, did anyone successfully authenticated using: 

``
await orango.connect('discovery', {
      url: 'http://127.0.0.1:8529',
      username: 'root',
      password: 'password'
}) 
``

I alwasy get: "ArangoError: not authorized to execute this request"

**Comment by redyce** [comment]
> Do you have a database called "discovery" with a user with those credentials that has access to that database?

Yes I do.
For some strange reason, using the root user caused the "not authorized" error, I created a specific user for that database and everything is fine now.

BTW, great job with orango, I am testing it at the company I work for :+1:

**Comment by roboncode** [comment]
Thx! Okay, I will look into it. Rob

**Comment by roboncode** [comment]
I have a fix, it will be included on my next release here shortly, i had the merge backwards, so it was overriding the params being passed in.

**Comment by roboncode** [comment]
0.9.4 release has the fix. The example also uses this.

```
orango.connect(db:String="_system", [{url:String="http://localhost:8529", username:String, password:String}])
```

**Comment by redyce** [comment]
> 0.9.4 release has the fix. The example also uses this.
> 
> ```
> orango.connect(db:String="_system", [{url:String="http://localhost:8529", username:String, password:String}])
> ```

Hello Rob, it works fine now :+1:
