### ISSUE TITLE
Timestamps - Default in Schema 

### ISSUE THREAD

**Issue by aguilera51284** [roboncode/orango#39]
I would like that this option is available, so as not to repeat code in the schemes, this as sequelize does.

http://docs.sequelizejs.com/manual/tutorial/models-definition.html#timestamps

**Comment by roboncode** [comment]
Thanks for the input. I can see how this could be useful in some situations. I will consider a solution when I address default properties within the library.

**Comment by roboncode** [comment]
So upon review and several trials for handling default values, I resolved the best way to handle default values such as a `createdAt` and `updatedAt` would be to do the following when defining your Model.

```js
const orango = require('orango')
const UserSchema = orango.Schema({
  name: String,
  createdAt: Date,
  updatedAt: Date
}, {
  strict: true
})

const User = orango.model('User', UserSchema)
User.on('create', (payload) => {
  payload.data.createdAt = Date.now()
})

User.on('update', (payload) => {
  payload.data.updatedAt = Date.now()
})

module.exports = User
```
I went the Occam's razor route on this one and felt this provides a way to handle unforeseen conditions in the simplest manor.
