### ISSUE TITLE
Count method

### ISSUE THREAD

**Issue by aguilera51284** [roboncode/orango#40]
i need get all documents in collection, Is there any method to do it?

**Comment by aguilera51284** [comment]
like sequelize findAndCountAll :+1:
 http://docs.sequelizejs.com/manual/tutorial/models-usage.html#-findandcountall-search-for-multiple-elements-in-the-database-returns-both-data-and-total-count

**Comment by roboncode** [comment]
You can get all documents using 
```js
const MyModel = orango.model('MyModel')
async function getDocs() {
   let docs = await MyModel.find()
   return docs
}
```

You can the number of docs using something like
```js
const User = orango.model('User')
async function getAdminUsers() {
   let count = await User.count({role: 'admin'})
   return count
}
```

Am I to understand that you are wanting a function that returns the results and pagination metadata?

**Comment by roboncode** [comment]
Closing issue. I assume the above answered your question.
