### ISSUE TITLE
Connecting to Multiple Databases

### ISSUE THREAD

**Issue by iraycd** [roboncode/orango#50]
```
      if (this.connected) {
        return reject(new Error(ERRORS.ALREADY_CONNECTED))
      }
```
is blocking me to connect with multiple databases. 
I wish there was support for connecting or using multiple databases. 

With plain ArangoJS. I do something like this.
```
// Using different databases
const db = new Database({
  url: "http://localhost:8529"
});
db.useDatabase("pancakes");
db.useBasicAuth("root", "");
// The database can be swapped at any time
db.useDatabase("waffles");
db.useBasicAuth("admin", "maplesyrup");
```

My use case is something similar to this:
https://github.com/EasyERP/EasyERP_open_source/blob/master/server.js

How do I achieve it?

-- PS
Thank you for making orango. I loved it.

**Comment by iraycd** [comment]
```js

let orango = require('../../../lib')

async function connectDatabase(dbName){
  const db = orango.get(dbName)
  if(!db.connection.connected){
    db.events.on('connected', (instanace) => {
      console.log(`Conneted to ${instanace.name}`)
    })
    await db.connect(dbName)
  }else{
    console.log(`Getting ${db.connection.name}`)
  }
  return db
}


async function main() {
  orango = await connectDatabase('sample2')
  orango = await connectDatabase('sample3')
  orango = await connectDatabase('sample2') // If Reconnect get sample2, instead of error.
  orango = await connectDatabase('sample3') // If Reconnect get sample2, instead of error.
  console.log(`Present database is ${orango.connection.name}`)
}

main()

```
This is a snippet which I have written.
But, I had to write `await db.connect(dbName)` to connect it, if you notice.
Is the following method any good?

```
Conneted to sample2
Conneted to sample3
Getting sample2
Getting sample3
Present database is sample3
```

**Comment by roboncode** [comment]
Thx. Yes you should be able to connect to multiple databases. To connect to multiple databases you should be able to use the following syntax. I use this in the unit tests...`test/index.js`

```js
const s1 = await orango.get('sample1').connect()
const s2 = await orango.get('sample2').connect()
const s3 = await orango.get('sample3').connect()
```

This creates a unique instance of each db connection and they should work independently from each other.

**Comment by roboncode** [comment]
I should also point out that with this approach models need to be registered / referenced with the appropriate instance...

```js
const s1 = orango.get('sample1')
s1.model('User', {
   email: String,
   firstName: String,
   lastName: String
}

const User = s1.model('User')
let u = new User()
...
```

**Comment by iraycd** [comment]
It’s based on purpose. I think my approach is better for this use case, as be your 
[api/_draft.md](https://github.com/roboncode/orango/blob/master/docs/api/__draft.md)

Please refer: https://github.com/roboncode/orango/pull/51 on how I am managing the models.js

**Comment by iraycd** [comment]
BTW, when I tried `await orango.get('sample1').connect()` is always goes to the `_system`

```
const s1 = await orango.get('sample1').connect()
const s2 = await orango.get('sample2').connect()
const s3 = await orango.get('sample3').connect()
```

I guess the above is approach is wrong, as we might have various authentication for databases. 
It's necessary that we mentions DB Name in connect too.
