### ISSUE TITLE
Testing with Jest

### ISSUE THREAD

**Issue by iraycd** [roboncode/orango#52]
https://www.valentinog.com/blog/testing-api-koa-jest/

Jest for testing instead of Chai/Mocha

**Comment by iraycd** [comment]
Instead of using 
```
    "chai": "4.2.0",
    "coveralls": "^3.0.2",
    "mocha": "^5.2.0",
    "nyc": "13.1.0",
```

You can just you `jest`

**Comment by iraycd** [comment]
See the PR, replaced multiple tests with jest:  https://github.com/roboncode/orango/pull/53

**Comment by roboncode** [comment]
Nice! Thank you very much. I am going to move the pull request in. There is an error showing up in Travis so not sure why but I will see if I can nail down what is causing that.

**Comment by roboncode** [comment]
Will you create another pull request for this again. I accidentally merged it into the wrong branch and had to revert it. Thx. Rob

**Comment by iraycd** [comment]
I have commented many tests, please check my repo and travis errors are due to code coverage.

It’s better if you play with my repo before you merge it.

**Comment by iraycd** [comment]
@roboncode Have you checked it?
