### ISSUE TITLE
ORM / ODM / OGM

### ISSUE THREAD

**Issue by iraycd** [roboncode/orango#57]
Object-graph mapping.
I don't know where this belongs, but Orango is a combination of ORM, ODM & OGM.
It's also ORM once it's supports Transactions: https://docs.arangodb.com/3.4/Manual/Transactions/

ORM, OGM and ODM.

ArangoDB as a specialized database for key/values, documents or graphs and even mix up those data models in one query.

ODGM??

**Comment by roboncode** [comment]
I will have to think about that one. Not sure what the right answer is.

**Comment by mihazs** [comment]
I suggest to be like the arangodb are defined, multi-model, so:
Object Multi-model Mapping 
OMMM
O3M
OMM

Something like this, I guess....

**Comment by roboncode** [comment]
In the end its still a ODM (Object Data Modeler)

**Comment by iraycd** [comment]
For SEO purpose we have to include ORM and OGM.
