### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by juicycleff** [roboncode/orango#60]
I was thinking of transforming the lib to Typescript if it is fine, firvtype safety and auto completion. I will help developers know what already exist in the library and can solve documentation issues by a half. Is this fine?

**Comment by iraycd** [comment]
I and @roboncode am with you on using Typescript.

https://github.com/roboncode/orango/tree/next
This is an active branch which we @roboncode is working on. It's changing every day. I think it would be stable soon.

> Right now I think, my focus is on:
> 1. finalize API for beta
> 2. stable code
> 3. documentation for API
>
> -- @roboncode

**Comment by roboncode** [comment]
It would be premature to convert it to Typescript at this point.
