### ISSUE TITLE
overriding toJSON  and including static isn't supports while using extends orango.Schema 

### ISSUE THREAD

**Issue by iraycd** [roboncode/orango#66]
```javascript
class AppSchema extends orango.Schema {
   toJSON() {
      let returnVal = Object.assign({}, this, { id: this._key })
      delete this._key
      delete this._rev
      delete this._id
      return returnVal
   }

   static async newRecord(data, type) {
    this.insert({...data, type}).return(orango.return.one())
   }
}
```
Both, toJSON() and static isn't working.

**Comment by roboncode** [comment]
I have been thinking about this one and how it should play out. The schema should define the document structure. The model implement functionality for the document. I have worked out a solution that achieves both. The example below is optional and could have been done by setting properties and functions on prototype or directly on the class after the model was registered. This is just something that seems a little more formalized in the implementation.

```js
module.exports = async ({ orango }) => {

  const schema = new orango.Schema({
    firstName: String,
    lastName: String
  })

  const PersonModel = orango.createModel(schema)

  class Person extends PersonModel {
    get name() {
      return this.firstName + ' ' + this.lastName
    }

    static newPerson(firstName, lastName) {
      return new Person({
        firstName,
        lastName
      })
    }

    toJSON() {
      return {
        firstName: this.firstName,
        lastName: this.lastName,
        name: this.name
      }
    }
  }

  orango.model(Person)

  let person = Person.newPerson('John', 'Smith')

  console.log(person) // Person { firstName: 'John', lastName: 'Smith' }
  console.log(JSON.stringify(person)) // {"firstName":"John","lastName":"Smith","name":"John Smith"}
  console.log('My name is', person.name) // My name is John Smith
}
```

It is something similar to what I had before making the change to schema, the difference is that this now separates the need from having to structure the class with a constructor that passes in the schema in an odd way. Also as mentioned above, this is completely optional. I have a few things to work out on it before I can add it.

**Comment by roboncode** [comment]
release v1.0.0-alpha-2.5
