### ISSUE TITLE
TypeError: Cannot set property host of #<IncomingMessage> which has only a getter

### ISSUE THREAD

**Issue by arnaudpoullet** [roboncode/orango#69]
I installed ArangoDB and Orango npm package on a clean Total.js install and after following the '[getting started - full usage example](https://orango.js.org/guide/getting-started.html#overview)' to the letter and starting the node app I got the following error:

> TypeError: Cannot set property host of #<IncomingMessage> which has only a getter
>     at _hosts.(anonymous function) (/home/default/projects/myapp/node_modules/arangojs/lib/async/connection.js:131:35)
>     at IncomingMessage.res.on (/home/default/projects/myapp/node_modules/arangojs/lib/async/util/request.node.js:78:21)
>     at emitNone (events.js:111:20)
>     at IncomingMessage.emit (events.js:208:7)
>     at endReadableNT (_stream_readable.js:1056:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
> ======= 2019-04-05 18:58:44: TypeError: Cannot set property host of #<IncomingMessage> which has only a getter TypeError: Cannot set property host of #<IncomingMessage> which has only a getter
>     at _hosts.(anonymous function) (/home/default/projects/myapp/node_modules/arangojs/lib/async/connection.js:131:35)
>     at IncomingMessage.res.on (/home/default/projects/myapp/node_modules/arangojs/lib/async/util/request.node.js:78:21)
>     at emitNone (events.js:111:20)
>     at IncomingMessage.emit (events.js:208:7)
>     at endReadableNT (_stream_readable.js:1056:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

Is this an actual error ? Or am I missing something (is nodejs 11.9 not supported?) that may be added to the getting started guide.

After a bit of looking and trying a few things I changed:
`response.host = host;`
on `node_modules/arangojs/lib/async/connection.js:131:35` to
`response._host = host;`
the error is gone. Did I break something by doing this or did I fix it?

**Comment by roboncode** [comment]
The modification you made is to the ArangoJS library. It looks like host may be a getter? dunno.

**Comment by roboncode** [comment]
I stubbed a Total.js and am able to see the error. I will see if it is ArangoJS / Orango / TotalJS.

**Comment by roboncode** [comment]
There is an issue in ArangoJS. The proper fix is to assign it to `task.host`. I have made a PR - https://github.com/arangodb/arangojs/pull/604

**Comment by roboncode** [comment]
Sure, thx. I am going to close it then. I have used Total.js in the past for some projects and it is a nice framework, but not well adopted.
