### ISSUE TITLE
Cannot read property 'queryToAQL' of undefined

### ISSUE THREAD

**Issue by arnaudpoullet** [roboncode/orango#70]
When I was trying to adapt [koa2-rest-api-boilerplate](https://github.com/HanHyeoksu/koa2-rest-api-boilerplate) to use orango instead of mongoose I got this error:
`Cannot read property 'queryToAQL' of undefined`
from
```
TypeError: Cannot read property 'queryToAQL' of undefined
    at QueryBuilder.qb.toAQL (/home/arnaud/projects/my-app2/node_modules/orango/lib/Model.js:77:32)
    at QueryBuilder.qb.then (/home/arnaud/projects/my-app2/node_modules/orango/lib/Model.js:111:26)
    at User.save (/home/arnaud/projects/my-app2/node_modules/orango/lib/Model.js:225:8)

```
 ArangoDB and Orango have successfully started at this point. The error is thrown when I call this method from my userService:

```
static async create(){
        let user = await User.newUser('11111111111',
            'green',
            '00000000'
        );
        await user.save(); // <-- error here
        return user.smallJSON();
    }
```

If I replace
`await user.save();`
with
`console.log(user)`
it returns a correctly formed JSON, so the structure of my app doesn't seem to be at fault.

My user model:

```
const orango = require('orango');
const { SCHEMA } = orango.consts;
let schema = new orango.Schema({
	fuid: {
		type: String, min: 10, default:-1
	},
	phone: {
		regex: /^\+\d{10,}$/,
	},
	email: {
		type: String, email: { minDomainAtoms: 2 }
	},
	emailConfirmed: {
		type: Boolean,default: false
	},
	password:{
		type: String
	},
	access_token: {
		type: [ String, Number ]
	},
	register_token:{
		type: String, required: true
	},
	color: {
		allow: ['green', 'red', 'blue'],
		required: true
	},
	dt_create:{
		type: Date,timestamp:'javascript',default: Date.now()
	},
	dt_update:{
		type: Date,timestamp:'javascript',default: Date.now()
	},
	disabled:{
		type:Boolean,default:false
	}
},{
	indexes: [
		{
			type: SCHEMA.INDEX.HASH,
			fields: ['email','phone','fuid']
		}
	]
});
const UserModel = orango.createModel(schema);
class User extends UserModel {
	static newUser(register_token,color,access_token){
		return new User({
			register_token: register_token,
			color: color,
			access_token: access_token,
			email: '',
			password: '',
			phone: ''
		})
	}
	smallJSON() {
		return {
			id: this._id,
			register_token: this.register_token,
			color: this.color
		}
	}
}
module.exports = orango.model('User',User);
```

**Comment by armenr** [comment]
I get the same exact behavior. I have been fighting with this error for the last 12 hours. I switched it up, and tried a different way, from the DOCS in the repo, and got an even weirder error:

```{ Message: 'Server startup fucked up!',
  Payload:
   TypeError: schema.init is not a function
       at Orango.createModel (/Users/armenr/Desktop/gruv-new/gruvzer0/node_modules/orango/lib/Orango.js:275:12)
       at Orango.model (/Users/armenr/Desktop/gruv-new/gruvzer0/node_modules/orango/lib/Orango.js:357:35)
       at start (/Users/armenr/Desktop/gruv-new/gruvzer0/packages/gruv-api/src/server.js:146:25)
       at Object.<anonymous> (/Users/armenr/Desktop/gruv-new/gruvzer0/packages/gruv-api/src/server.js:221:1)
       at Module._compile (internal/modules/cjs/loader.js:701:30)
       at loader (/Users/armenr/Desktop/gruv-new/gruvzer0/node_modules/babel-register/lib/node.js:144:5)
       at Object.require.extensions.(anonymous function) [as .js] (/Users/armenr/Desktop/gruv-new/gruvzer0/node_modules/babel-register/lib/node.js:154:7)
       at Module.load (internal/modules/cjs/loader.js:600:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
       at Function.Module._load (internal/modules/cjs/loader.js:531:3) }```

Snippet from server file:

```
    const db = orango.get('dev1');

    db.events.once(EVENTS.CONNECTED, (conn) => {
      console.log('🥑  Connected to ArangoDB:', conn.url + '/' + conn.name);
    });

    db.events.once(EVENTS.READY, () => {
      console.log('🍊  Models loaded, Orango is all good to go!');
    });

    const User = orango.model('User', {
      name: String,
      email: String,
    });

    orango.logger.level = 'debug';

     let user = new User({ name: 'Sample User', email: 'user@sample.com' });
     await user.save;

```

**Comment by roboncode** [comment]
Thanks for the kind words. I just got back from vacation. I will look into this and see what is up. Rob

**Comment by roboncode** [comment]
@armenr Here is a working version of your code example...

When you use `orango.get()`, you are creating a instance (singleton) of `orango`. This is so you can actually connect to multiple instances at the same time. So when you register your models, you also have to register it with that instance

```js
const db = orango.get('dev1')
db.model('User', ...)
```

Secondly, when you are registering a `model`, you will see that "currently" you need to pass it in as a `schema` instance, like so...

```js
  const User = db.model('User', new orango.Schema({
    name: String,
    email: String
  }))
```

The next version, I have added the ability to register the model like you had above...

```js
  const User = db.model('User', {
    name: String,
    email: String
  })
```

Finally, here is a working copy I tested with...

```js
const orango = require('orango')
const {EVENTS} = orango.consts

async function main() {
  const db = orango.get('dev1')

  db.events.once(EVENTS.CONNECTED, conn => {
    console.log('🥑  Connected to ArangoDB:', conn.url + '/' + conn.name)
  })

  db.events.once(EVENTS.READY, () => {
    console.log('🍊  Models loaded, Orango is all good to go!')
  })

  const User = db.model('User', new orango.Schema({
    name: String,
    email: String
  }))

  await db.connect({
    url: 'http://localhost:15100'
  })

  db.logger.level = 'debug'

  let user = new User({ name: 'Sample User', email: 'user@sample.com' })
  await user.save()
}

main()
```

**Comment by roboncode** [comment]
@arnaudpoullet - Do you have a repo I can checkout where you are making this change so I can test it? If I had a better context I am sure I can see where the issue is. Thx Rob

**Comment by roboncode** [comment]
Actually, I just created a Total.js project and I am able to see that error. I will see if it is something to do with ArangoJS / Total.js / Orango

**Comment by arnaudpoullet** [comment]
Hi,
Thank you so much for your reactivity. I think I have the same issue as @armenr, I instantiated a db but used 'orango'. It makes sense that it didn't work, that's what happens when we follow the DOCS blindly I suppose. :) Maybe this situation could throw an error that would make it clear we're supposed to use the db instance in case others make the same mistake ? Be it by distraction or misunderstanding.

**Comment by armenr** [comment]
@roboncode - YOU ARE THE MAN! Thank you for clarifying that and being so meticulous in responsiveness and helpfulness.

Seriously dude, you're awesome. My team and our project thank you for your help, as well as for this badass library.

**Comment by armenr** [comment]
So, new question, and please bear with me as I acknowledge this is a question only a n00b would ask, buuuuuttttttt, say I have the following setup

in my project, I have /src/connectors/
in connectors, I have a file lovingly named: `connectArango.js`

The contents of the file are:
```
// connectArango.js
import orango from 'orango';
const { EVENTS } = orango.consts;

async function connectArangoDB() {
  const graphDB = orango.get('dev1');

  graphDB.events.once(EVENTS.CONNECTED, (conn) => {
    console.log('🥑  Connected to ArangoDB:', conn.url + '/' + conn.name);
  });

  graphDB.events.once(EVENTS.READY, () => {
    console.log('🍊  Models loaded, Orango is all good to go!');
  });

  let arangoClient = await graphDB.connect({
    url: 'http://localhost:8529',
  });

  graphDB.logger.level = 'debug';
  return arangoClient;
}

module.exports.connectArangoDB = connectArangoDB;
```

In my server.js @ the project root, I have this:
```
// server.js (main server file)
import { NODE_ENV, HOST, PORT } from '@env';

import express from 'express';
import cors from 'cors';
import { loggerUtil, morganChalk } from './lib/constants.js';
import { testRouter, unknownRouter } from './routes';
import { handleErrors } from './middleware/errorHandler.js';
import { connectMongoDB } from './connectors/connectMongo';
import { connectArangoDB } from './connectors/connectArango';

const app = express();

const start = async () => {
  try {
    // initialize database connections
    await connectMongoDB();
    await connectArangoDB();

    // initialize Express Server
    app
      .use(morganChalk)
      .use(cors())
      .use(express.urlencoded({ extended: true }))
      .use(express.json())
      .set('json spaces', 2);

    //handle known routes
    // TODO: Refactor so that you can pass the toplevel routes from here:
    // Example: app.use('/testRoutes/, testRouter)
    app.use('/', testRouter);
    // app.use('/', authRouter);

    // handle unknown routes
    app.use('*', unknownRouter);

    // handle errors
    app.use(handleErrors);

    // Fire up the server!!
    await app.listen(PORT, HOST, () => {
      console.log({
        Message: 'Server Online! 🚀',
        Mode: `${NODE_ENV}`,
        Address: `http://${HOST}:${PORT}`,
      });
    });
  } catch (serverError) {
    loggerUtil('Server startup fucked it!', serverError);
  }
};

start();
```

In the Router file:
```
// testRouter.js
/**
 * router to handle testing
 */

import { loggerUtil } from '../lib/constants.js';
import { Router } from 'express';
const testRouter = Router();
import orango from 'orango';
const testDB = orango.get('test1');

const ArangoUserDocument = testDB.model(
  'User',
  new orango.Schema({
    name: String,
    email: String,
  }),
);

loggerUtil('TestDB Object', testDB);

testRouter.get('/test/test1', async (req, res, next) => {
  try {
    let arangoSampleUser = new ArangoUserDocument({ name: 'Sample User', email: 'user@sample.com' });
    await arangoSampleUser.save().then(res.send('ALL GOOD, BUD!'));
  } catch (error) {
    res.send('Errors thrown from test route in Express', error);
  }
});

export default testRouter;
```

So, I guess what I'm asking is, how do I structure this around the concept of singleton instances so that my routes don't leak connections? :-\ 

I know it's a bit of a long ask, but figured I'd try my luck. Thank you! :) 👍

**Comment by roboncode** [comment]
@armenr Good questions. Hopefully I answer them. If I don't then let me know. First, you can always get the same instance using `const db = orango.get(db:String)`, i.e.
```js
orango.get('mydb') === orango.get('mydb') // true
```
If you want to do something a little more sophisticated such as DI (Dependency Inject) then look at the https://github.com/orangojs/orango-examples. There I pass in the orango instance into each function that needs to use it.

**Comment by armenr** [comment]
^^ Dude. You're the man. At this point, I feel as though I might be abusing this thread as an "Issue." 

You've answered my questions. I am most grateful. I completely understand how to use all of this, at this point. 

Is there a slack, or a spectrum community, or a gitter for Orango? My team and I would be very active in there, and I think it might help for communication between us, as well as communication with others that might come to your library with questions. As we learn, we're happy to provide answers to others too :) 

We're a community. 👍

**Comment by roboncode** [comment]
thx. Discord Community - https://discordapp.com/invite/7fHadJj
